### ISSUE TITLE
Missing module 

### ISSUE THREAD

**Issue by pdavisjones** [labnol/apps-script-starter#11]
I'm having trouble replicating your steps. I've tried multiple times, and it looks like something with webpack is malfunctioning. It's preventing me from compiling my work:

```
/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/cli.js:74
                                throw err;
                                ^

Error: Cannot find module './node_modules/gas-webpack-plugin/node_modules/gas-entry-generator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/gas-webpack-plugin/index.js:3:27)
    at Module._compile (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/webpack.config.js:13:19)
    at Module._compile (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/utils/convert-argv.js:115:13)
    at requireConfig (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/utils/convert-argv.js:117:6)
    at /Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/utils/convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/utils/convert-argv.js:122:15)
    at yargs.parse (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/cli.js:71:45)
    at Object.parse (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/yargs/yargs.js:567:18)
    at /Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack-cli/bin/cli.js:368:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/pdavisjones/Documents/Coding/apps-script/honeybee4/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apps-script-starter@3.4.1 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apps-script-starter@3.4.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdavisjones/.npm/_logs/2019-05-17T22_36_22_012Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! apps-script-starter@3.4.1 deploy: `npm run build && npm run upload`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apps-script-starter@3.4.1 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pdavisjones/.npm/_logs/2019-05-17T22_36_22_037Z-debug.log
```

**Comment by ckalegi** [comment]
@labnol Mind documenting the versions of Node & NPM you used in the video? I see Node 10.12 but wonder if using the specific NPM version would alleviate the issue

**Comment by unncommon** [comment]
I have the same error, can't compile the code as per the video instructions.

NPM v6.4.1
NODE v10.13.0

**Comment by nk-gears** [comment]
I tried with the package  clean-webpack-plugin  2.0.1 and it works good.

**Comment by oshliaer** [comment]
@pdavisjones 

> Error: Cannot find module './node_modules/gas-webpack-plugin/node_modules/gas-entry-generator'

Please share your package.json & package-lock.json. Also check he path `./node_modules/gas-webpack-plugin/node_modules/gas-entry-generator` for existing files.

**Comment by oshliaer** [comment]
@unncommon 

I'm afraid it's not the same issue.

**Comment by unncommon** [comment]
I had to change webpack.config.js and add brackets around CleanWebpackPlugin :

`const { CleanWebpackPlugin } = require('clean-webpack-plugin’);`

All working well now. Thank you.

**Comment by labnol** [comment]
Thanks!
